"""
The attribution registry.

PLAN.md §5: "The attribution file is generated by the pipeline, never
hand-written." Rows carry a short `source_id`; the full citation and licence
live here once and are written out to `pipeline/artifacts/sources.json`, which
the loader reads to fill the `source` and `license` columns.

A missing attribution is a licence breach, so the loader fails rather than
guesses (PLAN.md §4) — which only works if every id used by a stage is
registered here.
"""

import json
from pathlib import Path

ARTIFACTS = Path(__file__).resolve().parents[1] / "artifacts"

SOURCES: dict[str, dict[str, str]] = {
    "cefr-j": {
        "name": "CEFR-J Vocabulary Profile v1.5",
        "attribution": "Tono Laboratory, Tokyo University of Foreign Studies",
        "url": "https://github.com/openlanguageprofiles/olp-en-cefrj",
        "license": "CC BY-SA 4.0",
        "commercial": "yes, with citation",
        "note": "Levels A1-B2.",
    },
    "octanove": {
        "name": "Octanove Vocabulary Profile C1/C2 v1.0",
        "attribution": "Octanove Labs",
        "url": "https://github.com/openlanguageprofiles/olp-en-cefrj",
        "license": "CC BY-SA 4.0",
        "commercial": "yes, with citation",
        "note": "Levels C1-C2, distributed alongside CEFR-J.",
    },
    "wiktextract-it": {
        "name": "Wiktionary (English edition) Italian entries, via kaikki.org / wiktextract",
        "attribution": "Wiktionary contributors; extraction by Tatu Ylonen (kaikki.org)",
        "url": "https://kaikki.org/dictionary/Italian/",
        "license": "CC BY-SA 4.0 and GFDL",
        "commercial": "yes, with attribution and share-alike",
        "note": "English glosses for Italian lemmas - the it-from-en direction.",
    },
    "wiktextract-en": {
        "name": "Wiktionary (English edition) English entries, via kaikki.org / wiktextract",
        "attribution": "Wiktionary contributors; extraction by Tatu Ylonen (kaikki.org)",
        "url": "https://kaikki.org/dictionary/English/",
        "license": "CC BY-SA 4.0 and GFDL",
        "commercial": "yes, with attribution and share-alike",
        "note": "German translations for English lemmas - the en-from-de direction.",
    },
    "nvdb": {
        "name": "Nuovo vocabolario di base della lingua italiana (2016)",
        "attribution": "Tullio De Mauro and Isabella Chiari, with Francesca Ferrucci; machine-readable extraction by Alberto Pettarin",
        "url": "https://github.com/pettarin/nvdb",
        "license": "Public Domain (extraction)",
        "commercial": "extraction yes; the underlying selection is editorial - see PLAN.md §5",
        "note": "Usage bands FO/AU/AD are recovered from the PDF typography; the plain-text extraction does not carry them.",
    },
}


def resolve(source_id: str) -> dict[str, str]:
    if source_id not in SOURCES:
        raise KeyError(f"unregistered source id: {source_id}")
    return SOURCES[source_id]


def write_manifest(used: set[str]) -> Path:
    """Write sources.json covering every id the artifacts actually use."""
    unknown = sorted(used - SOURCES.keys())
    if unknown:
        raise KeyError(f"unregistered source ids in artifacts: {unknown}")

    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    path = ARTIFACTS / "sources.json"

    existing: dict[str, dict[str, str]] = {}
    if path.exists():
        existing = json.loads(path.read_text(encoding="utf-8"))

    merged = {**existing, **{sid: SOURCES[sid] for sid in sorted(used)}}
    path.write_text(
        json.dumps(merged, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return path
